### ISSUE TITLE
Is there a command to install pip onto CMD?

### ISSUE THREAD

**Issue by ZekePolarisBSH** [Riot-Byte/hydra-mass-dm#1]
I am trying to use this but for some odd reason I can install everything else but not PIP... Any ideas? I know it isn't the hydra, I think it has something to do with my system.

**Comment by Riot-Byte** [comment]
u need python (add it to path too) https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe

**Comment by ZekePolarisBSH** [comment]
Sorry, can we use Discord? That way I don't accidently spam here... Because I have that installed and added to path but it still giving me the same issues. That is why I said something must be wrong with my device... Also, thanks for replying!
